### ISSUE TITLE
Runtime ERROR

### ISSUE THREAD

**Issue by JamesKnight0001** [arcee-ai/mergekit#121]
```

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\Scripts\mergekit-yaml.exe\__main__.py", line 4, in <module>
  File "C:\Users\irene\OneDrive\Desktop\JamesCoder\mergekit\mergekit\scripts\run_yaml.py", line 21, in <module>
    from mergekit.config import MergeConfiguration
  File "C:\Users\irene\OneDrive\Desktop\JamesCoder\mergekit\mergekit\config.py", line 22, in <module>
    from mergekit.common import ModelReference
  File "C:\Users\irene\OneDrive\Desktop\JamesCoder\mergekit\mergekit\common.py", line 23, in <module>
    import peft
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\mapping.py", line 23, in <module>
    from .peft_model import (
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\peft_model.py", line 38, in <module>
    from .tuners import (
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\lora\__init__.py", line 21, in <module>
    from .model import LoraModel
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\lora\model.py", line 45, in <module>
    import bitsandbytes as bnb
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
 ```

**Comment by cg123** [comment]
I'm afraid I don't think I can help you much with this - this looks like a Windows-specific problem with your CUDA setup. I'd strongly recommend using WSL if you want to use mergekit on a Windows machine. If you need to run it on base Windows, though, I'd suggest trying installing Python through [anaconda](https://www.anaconda.com/download). The few times I've dealt with pytorch CUDA on Windows it was pretty painless getting things set up that way.

Sorry I'm not more help here!
