### ISSUE TITLE
moe.md missing

### ISSUE THREAD

**Issue by NtaylorOX** [arcee-ai/mergekit#135]
Amazing work - although I am struggling to get the mixtral_moe.py script to work, and the related .md file referenced elsewhere is now missing? The link was: https://github.com/cg123/mergekit/blob/mixtral/moe.md 

Do you have an example of how to run this script to merge a couple of models?

**Comment by cg123** [comment]
Sorry about that - I moved `moe.md` into the `docs` folder. Here's the current link: https://github.com/cg123/mergekit/blob/mixtral/docs/moe.md

**Comment by NtaylorOX** [comment]
No problem - in hindsight I should have looked better.

Although, I do have a follow up problem. When running the following code:

```
python mixtral_moe.py ../../configs/mergekit_moe_config.yaml ../../test_models/ 
```

With the following config (ignore the fact its a dumb config):

```json
base_model: microsoft/phi-2
gate_mode: cheap_embed
experts:
  - source_model: vince62s/phi-2-psy
    positive_prompts: ["Psychology", "Psychological"]
  - source_model: cognitivecomputations/dolphin-2_6-phi-2
    positive_prompts: ["Maths", "Mathematics"]
```

I run into the following error:

```
Traceback (most recent call last):
  File "/home/niallt/mergekit/mergekit/scripts/mixtral_moe.py", line 469, in <module>
    main()
  File "/home/niallt/.pyenv/versions/311_llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niallt/.pyenv/versions/311_llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/niallt/.pyenv/versions/311_llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niallt/.pyenv/versions/311_llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niallt/mergekit/mergekit/options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "/home/niallt/mergekit/mergekit/scripts/mixtral_moe.py", line 450, in main
    build(
  File "/home/niallt/mergekit/mergekit/scripts/mixtral_moe.py", line 325, in build
    tensor = base_loader.get_tensor(tensor_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niallt/mergekit/mergekit/io/lazy_tensor_loader.py", line 127, in get_tensor
    raise KeyError(key)
KeyError: 'model.norm.weight'
```

To my knowledge, these are models others have merged successfully before, so not entirely sure what is going on here.

Any insight would be much appreciated.

Again, really nice work!

**Comment by NtaylorOX** [comment]
Sorry, I now realise the above problem is linked to the fact your code is expecting a "mistral/mixtral" model, rather than the Phi2 model architecture. 

Do you happen to have any working code for the Phi models?
