### ISSUE TITLE
moe-mixtral error: "AttributeError: 'JsonArchitectureInfo' object has no attribute 'pre_weight_names'. Did you mean: 'pre_weights'?"

### ISSUE THREAD

**Issue by nkotak** [arcee-ai/mergekit#163]
I got this issue that came up:

```
`Fetching 11 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 82831.86it/s]
Fetching 8 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 74731.47it/s]
Fetching 13 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 111962.94it/s]
Fetching 10 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 42196.22it/s]
Fetching 11 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 127804.28it/s]
Warm up loaders: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  8.70it/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/mergekit-moe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neal/AI/mergekit/mergekit/options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "/Users/neal/AI/mergekit/mergekit/scripts/mixtral_moe.py", line 453, in main
    build(
  File "/Users/neal/AI/mergekit/mergekit/scripts/mixtral_moe.py", line 325, in build
    for tensor_name in MISTRAL_INFO.pre_weight_names + MISTRAL_INFO.post_weight_names:
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'JsonArchitectureInfo' object has no attribute 'pre_weight_names'. Did you mean: `'pre_weights'?``
```
I changed the line to pre_weights(config) and post_weights(config): in the moe-mixtral script but eventually couldnt get passed that.

**Comment by cg123** [comment]
Thanks for reporting this! It should be fixed now - do let me know if it gives you any futher trouble.
