### ISSUE TITLE
Gemma support isnt working on latest verison

### ISSUE THREAD

**Issue by rombodawg** [arcee-ai/mergekit#178]
When using latest version and trying to merge Gemma using (task_arithmatic) method this error comes up. (Sorry for the weird file names)

```
D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit>mergekit-yaml D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\examples\Sauronties.yml "E:\Open_source_ai_chatbot\OOBA_8\text-generation-webui-main\models\GemmaMerge-7b"
C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit\options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit\scripts\run_yaml.py", line 47, in main
    run_merge(
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit\merge.py", line 45, in run_merge
    model_arch_info = [
                      ^
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit\merge.py", line 46, in <listcomp>
    get_architecture_info(m.config(trust_remote_code=options.trust_remote_code))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Merging_models_on_D_drive\mergekit3-gemma\mergekit\mergekit\common.py", line 121, in config
    return AutoConfig.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\models\auto\configuration_auto.py", line 1098, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\models\auto\configuration_auto.py", line 795, in __getitem__
    raise KeyError(key)
KeyError: 'gemma'
```

Here is my .yaml file

Sauronties.yml
```
models:
  - model: E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\gemma-7b-it-fp16
    parameters:
      weight: 1
  - model: E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\CorticalStack_gemma-7b-ultrachat-sft
    parameters:
      weight: 1
  - model: E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\cloudyu_google-gemma-7b-it-dpo-v1
    parameters:
      weight: 1
  - model: E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\abideen_gemma-7b-openhermes
    parameters:
      weight: 1
merge_method: task_arithmetic
base_model: E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\gemma-7b-base
parameters:
  normalize: true
  int8_mask: true
dtype: float16
```

**Comment by cg123** [comment]
Hey! This is because the version of `transformers` you have installed is from before Gemma got merged in. If you run `pip install -U transformers` you should be able to do this merge.
