### ISSUE TITLE
Unsupported architecture, GPTBigCodeForCausalLM

### ISSUE THREAD

**Issue by Jazgomez96** [arcee-ai/mergekit#188]
I am attempting to merge models and receive this error:
--copy-tokenizer --allow-crimes --out-shard-size 1B          
Could not find platform independent libraries <prefix>                                                                                              
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\JazmineGomez\Desktop\github_vs\mergekit\.venv\Scripts\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "c:\Users\JazmineGomez\Desktop\github_vs\mergekit\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\JazmineGomez\Desktop\github_vs\mergekit\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "c:\Users\JazmineGomez\Desktop\github_vs\mergekit\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\JazmineGomez\Desktop\github_vs\mergekit\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JazmineGomez\Desktop\github_vs\mergekit\mergekit\options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "C:\Users\JazmineGomez\Desktop\github_vs\mergekit\mergekit\scripts\run_yaml.py", line 47, in main
    run_merge(
  File "C:\Users\JazmineGomez\Desktop\github_vs\mergekit\mergekit\merge.py", line 46, in run_merge
    get_architecture_info(m.config(trust_remote_code=options.trust_remote_code))
  File "C:\Users\JazmineGomez\Desktop\github_vs\mergekit\mergekit\architecture.py", line 324, in get_architecture_info
    raise RuntimeError(f"Unsupported architecture {arch_name}")
RuntimeError: Unsupported architecture GPTBigCodeForCausalLM

**Comment by cg123** [comment]
This should be supported now! If it gives you any more trouble let me know.
