### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'nbytes'

### ISSUE THREAD

**Issue by umarbutler** [arcee-ai/mergekit#232]
Attempting to merge models on Python 3.11 on Windows 11 has yieled the following error for me: `AttributeError: 'Tensor' object has no attribute 'nbytes'`. I resolved it by installing the latest release of `mergekit` (v0.0.4) instead of the current repository. This issue may be the result of #221.

See the traceback below:
```powershell
PS D:\workspace\llms> mergekit-yaml ################.yml ./################ --cuda --random-seed 42
bin C:\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Fetching 9 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<?, ?it/s]
Fetching 13 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<?, ?it/s] 
Warmup loader cache: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.46it/s] 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.64it/s]
  6%|██████▉                                                                                                             | 125/2098 [00:01<00:24, 79.68it/s] 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\llms\mergekit\mergekit\options.py", line 78, in wrapper
    f(*args, **kwargs)
  File "D:\workspace\llms\mergekit\mergekit\scripts\run_yaml.py", line 47, in main
    run_merge(
  File "D:\workspace\llms\mergekit\mergekit\merge.py", line 87, in run_merge
    for _task, value in exec.run():
  File "D:\workspace\llms\mergekit\mergekit\graph.py", line 191, in run
    res = task.execute(**arguments)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\llms\mergekit\mergekit\io\tasks.py", line 168, in execute
    writer.save_tensor(name=self.tensor_name, tensor=tensor, clone=self.clone)
  File "D:\workspace\llms\mergekit\mergekit\io\tensor_writer.py", line 64, in save_tensor
    self.total_size += tensor.nbytes
                       ^^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'nbytes'. Did you mean: 'byte'?
```

**Comment by cg123** [comment]
Thanks for the report! I guess `nbytes` is a relatively recent addition to pytorch. This should be fixed on main now.

**Comment by umarbutler** [comment]
Awesome, thank you :)
