### ISSUE TITLE
RuntimeError: Tensor model.final_layernorm.weight required but not present in model 

### ISSUE THREAD

**Issue by jomangbp** [arcee-ai/mergekit#239]
fatal: destination path 'mergekit' already exists and is not an empty directory.
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for mergekit (pyproject.toml) ... done
mergekit-yaml config.yaml merge --copy-tokenizer --allow-crimes --out-shard-size 1B --lazy-unpickle --cuda --low-cpu-memory --trust-remote-code
Warmup loader cache:   0% 0/3 [00:00<?, ?it/s]
Fetching 10 files: 100% 10/10 [00:00<00:00, 100102.72it/s]
Warmup loader cache:  33% 1/3 [00:00<00:00,  4.11it/s]
Fetching 10 files: 100% 10/10 [00:00<00:00, 38409.38it/s]
Warmup loader cache:  67% 2/3 [00:00<00:00,  3.90it/s]
Fetching 5 files: 100% 5/5 [00:00<00:00, 24966.10it/s]
Warmup loader cache: 100% 3/3 [00:19<00:00,  6.62s/it]
  0% 1/2720 [00:00<00:02, 962.44it/s]
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/mergekit/mergekit/options.py", line 78, in wrapper
    f(*args, **kwargs)
  File "/content/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/content/mergekit/mergekit/merge.py", line 87, in run_merge
    for _task, value in exec.run():
  File "/content/mergekit/mergekit/graph.py", line 191, in run
    res = task.execute(**arguments)
  File "/content/mergekit/mergekit/io/tasks.py", line 76, in execute
    raise RuntimeError(
RuntimeError: Tensor model.final_layernorm.weight required but not present in model databricks/dolly-v2-3b

**Comment by ashmalvayani** [comment]
@jomangbp how did you solve this error? I am also trying to merge two models llama 3 and qwen but it's throwing me an error similar to yours. I added --allow-crimes but it did not solve my problem.
