### ISSUE TITLE
Evolutionary Merging out of memory

### ISSUE THREAD

**Issue by ArcherShirou** [arcee-ai/mergekit#341]
I'm experiencing an 80G A100 memory overflow issue when merging three 14B LLMs on a custom task using mergekit-evolve.  Could you please advise on 4-bit quantized model merging support or alternative solutions?

**Comment by cg123** [comment]
Could you share a stack trace please? It'd be helpful to know where exactly the OOM is occurring.

There are a few options to resolve this depending on the source. Merging in 4-bit is not supported. Evaluation in 4 or 8 bit precision can be done using #332, with some caveats - it doesn't support vLLM or in-memory merging. Disabling in-memory merging (`--no-in-memory`) could also be helpful. If the individual model merge operations are OOMing, which would be quite unusual, then you can run them on CPU (`--no-merge-cuda`) if they would fit in RAM instead.

**Comment by ArcherShirou** [comment]
Thanks  for your response. However, I still encountered a memory overflow issue after following your suggestion. I've tried three times, and below is the detailed:
1. Firstly, my startup script and configuration files are as follows:
```bash
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
mergekit-evolve eval_merge_config.yml \
    --storage-path /mnt/qwen_evol_merge_v1 \
    --task-search-path eval_tasks \
    --vllm \
    --no-in-memory \
    --no-merge-cuda \
    --no-wandb 
```
```YAML
genome:
    models:
      - models--YeungNLP--firefly-qwen1.5-en-14b-dpo-v0.1
      - qwen1.5-14B-stock-v0
    merge_method: task_arithmetic
    base_model:  Qwen1.5-14B-Chat
    layer_granularity: 8 # sane default
    allow_negative_weights: true # useful with task_arithmetic
tasks:
  - name: my_task
    weight: 1.0
```
2. set _--in-memory_  and _--merge-cuda_
`Traceback (most recent call last): 
  File "/root/miniconda3/envs/mergekit/bin/mergekit-evolve", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 336, in main
    run_merge(best_config, os.path.join(storage_path, "final_model"), merge_options)
  File "/mnt/mergekit/mergekit/merge.py", line 92, in run_merge
    for _task, value in exec.run(quiet=options.quiet):
  File "/mnt/mergekit/mergekit/graph.py", line 197, in run
    res = task.execute(**arguments)
  File "/mnt/mergekit/mergekit/merge_methods/generalized_task_arithmetic.py", line 110, in execute
    tvs, base = get_task_vectors(
  File "/mnt/mergekit/mergekit/merge_methods/generalized_task_arithmetic.py", line 195, in get_task_vectors
    delta = x - base
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.45 GiB. GPU 0 has a total capacty of 79.33 GiB of which 1.39 GiB is free. Process 1238885 has 4.76 GiB memory in use. Process 1245304 has 73.15 GiB memory in use. Of the allocated memory 4.35 GiB is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

3. set _--no-in-memory_ and _--merge-cuda_
`Traceback (most recent call last):                                                                                                        
  File "/root/miniconda3/envs/mergekit/bin/mergekit-evolve", line 8, in <module>                                                          
    sys.exit(main())                                                                                                                      
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__                                
    return self.main(*args, **kwargs)                                                                                                     
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main                                    
    rv = self.invoke(ctx)                                                                                                                 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                        
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke                                   
    return __callback(*args, **kwargs)                                                                                                    
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 312, in main                                                                      
    xbest, es = cma.fmin2(                                                                                                                
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4392, in fmin2                       
    res = fmin(objective_function, x0, sigma0,                                                                                            
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4818, in fmin                        
    X, fit = es.ask_and_eval(parallel_objective or objective_function,                                                                    
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 2479, in ask_and_eval                
    fit_first = func(X_first, *args)                                                                                                      
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 271, in parallel_evaluate                                                         
    res = strat.evaluate_genotypes(x)                                                                                                     
  File "/mnt/mergekit/mergekit/evo/strategy.py", line 100, in evaluate_genotypes                                                          
    return list(                                                                                                                          
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 113, in get_generator                   
    yield self.get_next()
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 309, in get_next
    return ray.get(future)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OutOfMemoryError): ray::OnDiskMergeEvaluator.evaluate_genotype() (pid=196786, ip=10.181.199.221, actor_id=75f7
f5ccc4a08d06a442c40d01000000, repr=<mergekit.evo.actors.OnDiskMergeEvaluator object at 0x7f8e97ac6ad0>)
  File "/mnt/mergekit/mergekit/evo/actors.py", line 101, in evaluate_genotype
    merged_path = merge_model(
  File "/mnt/mergekit/mergekit/evo/helpers.py", line 117, in merge_model
    run_merge(cfg, out_path=res, options=merge_options)
  File "/mnt/mergekit/mergekit/merge.py", line 92, in run_merge
    for _task, value in exec.run(quiet=options.quiet):
  File "/mnt/mergekit/mergekit/graph.py", line 197, in run
    res = task.execute(**arguments)
  File "/mnt/mergekit/mergekit/merge_methods/generalized_task_arithmetic.py", line 155, in execute
    mixed_delta = weighted_deltas.sum(dim=0)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.90 GiB. GPU 0 has a total capacty of 79.33 GiB of which 2.66 GiB is free. Process 1269034 has 76.65 GiB memory in use. Of the allocated memory 75.02 GiB is allocated by PyTorch, and 47.99 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

4. set _--in-memory_ and _--no-merge-cuda_
`Traceback (most recent call last):                                                                                                        
  File "/root/miniconda3/envs/mergekit/bin/mergekit-evolve", line 8, in <module>                                                          
    sys.exit(main())                                                                                                                      
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__                                
    return self.main(*args, **kwargs)                                                                                                     
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main                                    
    rv = self.invoke(ctx)                                                                                                                 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                        
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke                                   
    return __callback(*args, **kwargs)                                                                                                    
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 312, in main                                                                      
    xbest, es = cma.fmin2(                                                                                                                
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4392, in fmin2                       
    res = fmin(objective_function, x0, sigma0,                                                                                            
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4818, in fmin                        
    X, fit = es.ask_and_eval(parallel_objective or objective_function,                                                                    
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 2479, in ask_and_eval                
    fit_first = func(X_first, *args)                                                                                                      
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 271, in parallel_evaluate                                                         
    res = strat.evaluate_genotypes(x)                                                                                                     
  File "/mnt/mergekit/mergekit/evo/strategy.py", line 100, in evaluate_genotypes                                                          
    return list(                                                                                                                          
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 113, in get_generator                   
    yield self.get_next()                                                                                                                 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 309, in get_next                        
    return ray.get(future)   
File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OutOfMemoryError): ray::InMemoryMergeEvaluator.evaluate_genotype() (pid=204136, ip=10.181.199.221, actor_id=cf
55018583f7026f9bb23f3601000000, repr=<mergekit.evo.actors.InMemoryMergeEvaluator object at 0x7f67ec3d7c10>)
  File "/mnt/mergekit/mergekit/evo/actors.py", line 324, in evaluate_genotype
    return self.evaluate(genotype) 
  File "/mnt/mergekit/mergekit/evo/actors.py", line 311, in evaluate
    return _eval_model(
  File "/mnt/mergekit/mergekit/evo/helpers.py", line 45, in _eval_model
    results = lm_eval.evaluator.simple_evaluate(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/evaluator.py", line 234, in simple_evaluate
    results = evaluate(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/evaluator.py", line 373, in evaluate
    resps = getattr(lm, reqtype)(cloned_reqs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/api/model.py", line 329, in loglikelihood
    return self._loglikelihood_tokens(new_reqs, disable_tqdm=disable_tqdm)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/models/vllm_causallms.py", line 378, in _loglikelihood_tokens
    outputs = self._model_generate(requests=inputs, generate=False)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/models/vllm_causallms.py", line 211, in _model_generate
outputs = self.model.generate( 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 182, in generate
    return self._run_engine(use_tqdm)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 208, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 817, in step
    all_outputs = self._run_workers(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1014, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/worker/worker.py", line 223, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list, 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 582, in execute_model
    output = self.model.sample(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 296, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 105, in forward
    logprobs = torch.log_softmax(logits, dim=-1, dtype=torch.float)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.00 GiB. GPU 0 has a total capacty of 79.33 GiB of which 303.81 MiB isfree. Process 1281926 has 79.01 GiB memory in use. Of the allocated memory 77.28 GiB is allocated by PyTorch, and 157.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

5. set _--no-in-memory_ and _--no-merge-cuda_
`Traceback (most recent call last):                                                                                               [69/1941]
  File "/root/miniconda3/envs/mergekit/bin/mergekit-evolve", line 8, in <module>                                                          
    sys.exit(main())                                                                                                                      
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__                                
    return self.main(*args, **kwargs)                                                                                                     
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main                                    
    rv = self.invoke(ctx)                                                                                                                 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                        
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke                                   
    return __callback(*args, **kwargs)                                                                                                    
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 312, in main                                                                      
    xbest, es = cma.fmin2(                                                                                                                
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4392, in fmin2                       
    res = fmin(objective_function, x0, sigma0,                                                                                            
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 4818, in fmin                        
    X, fit = es.ask_and_eval(parallel_objective or objective_function,                                                                    
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/cma/evolution_strategy.py", line 2479, in ask_and_eval                
    fit_first = func(X_first, *args)                                                                                                      
  File "/mnt/mergekit/mergekit/scripts/evolve.py", line 271, in parallel_evaluate                                                         
    res = strat.evaluate_genotypes(x)                                                                                                     
  File "/mnt/mergekit/mergekit/evo/strategy.py", line 100, in evaluate_genotypes                                                          
    return list(                                                                                                                          
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 113, in get_generator                   
    yield self.get_next()                                                                                                                 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/util/actor_pool.py", line 309, in get_next
    return ray.get(future)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OutOfMemoryError): ray::OnDiskMergeEvaluator.evaluate_genotype() (pid=211215, ip=10.181.199.221, actor_id=12e0
133b765f4051b02409a001000000, repr=<mergekit.evo.actors.OnDiskMergeEvaluator object at 0x7f83794aead0>)
  File "/mnt/mergekit/mergekit/evo/actors.py", line 109, in evaluate_genotype
    return evaluate_model(
  File "/mnt/mergekit/mergekit/evo/helpers.py", line 86, in evaluate_model
    res = _eval_model(
  File "/mnt/mergekit/mergekit/evo/helpers.py", line 45, in _eval_model
    results = lm_eval.evaluator.simple_evaluate(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/evaluator.py", line 154, in simple_evaluate
    lm = lm_eval.api.registry.get_model(model).create_from_arg_obj(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/api/model.py", line 155, in create_from_arg_obj
    return cls(**arg_dict, **additional_config)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/lm_eval/models/vllm_causallms.py", line 97, in __init__
    self.model = LLM(**self.model_args)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 109, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 371, in from_engine_args
    engine = cls(*engine_configs,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 120, in __init__
    self._init_workers()
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 164, in _init_workers
    self._run_workers("load_model")
File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1014, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/worker/worker.py", line 100, in load_model
    self.model_runner.load_model() 
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 84, in load_model
    self.model = get_model(self.model_config, self.device_config,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 79, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 276, in __init__
    self.model = Qwen2Model(config, linear_method)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 238, in __init__
    self.layers = nn.ModuleList([
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 239, in <listcomp>
    Qwen2DecoderLayer(config, layer_idx, linear_method)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 173, in __init__
    self.self_attn = Qwen2Attention(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 125, in __init__
    self.o_proj = RowParallelLinear(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 494, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 55, in create_weights
    weight = Parameter(torch.empty(output_size_per_partition,
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacty of 79.33 GiB of which 5.81 MiB is 
free. Process 1295850 has 79.30 GiB memory in use. Of the allocated memory 77.54 GiB is allocated by PyTorch, and 191.79 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See document ation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
The entire traceback is provided above. Would you please take a look and offer your guidance on an appropriate solution?

**Comment by umiyuki** [comment]
I don't know if this is related, but it seems that quantization support with BitSandBytes has recently been implemented in vLLM. If this allows Mergekit-Evolve to also support quantization in vLLM, that would be very helpful.
https://github.com/bd-iaas-us/vllm/commit/126e816b6975e825c4c3bc42bb06bd38015857e2

**Comment by zymko** [comment]
I met the same proble while trying to merging two 70B models. Does mergekit support model/pipeline parallelism?
