### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (8192,28672) (8192,24576) 

### ISSUE THREAD

**Issue by ashmalvayani** [arcee-ai/mergekit#343]
Config file to reproduce:

```
base_model: meta-llama/Meta-Llama-3-70B-Instruct
dtype: bfloat16
merge_method: slerp
parameters:
  t:
  - filter: self_attn
    value:
    - 0
    - 0.5
    - 0.3
    - 0.7
    - 1
  - filter: mlp
    value:
    - 1
    - 0.5
    - 0.7
    - 0.3
    - 0
  - value: 0.5
slices:
- sources:
  - layer_range:
    - 0
    - 80
    model: freewheelin/free-evo-qwen72b-v0.8-re
  - layer_range:
    - 0
    - 80
    model: meta-llama/Meta-Llama-3-70B-Instruct
```

Error Trace:
```
Warmup loader cache: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.18s/it]
Executing graph:   0%|                                                                                                                                                  | 3/3617 [00:05<1:44:29,  1.73s/it]WARNING:root:Using common submatrix of size torch.Size([128256, 8192]) for lm_head.weight
Executing graph:   0%|▎                                                                                                                                                 | 7/3617 [00:35<5:37:16,  5.61s/it]WARNING:root:Using common submatrix of size torch.Size([128256, 8192]) for model.embed_tokens.weight
Executing graph:   1%|▊                                                                                                                                                | 19/3617 [00:53<2:47:34,  2.79s/it]
Traceback (most recent call last):
  File "/home/ashmal.vayani/anaconda3/envs/mergekit/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/ashmal.vayani/anaconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashmal.vayani/anaconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ashmal.vayani/anaconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashmal.vayani/anaconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/merge.py", line 92, in run_merge
    for _task, value in exec.run(quiet=options.quiet):
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/graph.py", line 197, in run
    res = task.execute(**arguments)
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/merge_methods/slerp.py", line 57, in execute
    slerp(
  File "/mnt/beegfs/fahad.khan/Arabic_MobiLlama/mergekit/mergekit/merge_methods/slerp.py", line 134, in slerp
    dot = np.sum(v0 * v1)
ValueError: operands could not be broadcast together with shapes (8192,28672) (8192,24576) 
```

**Comment by cg123** [comment]
Qwen 72B and Llama 70B have different parameter sizes (and were trained from different initializations), so unfortunately these models aren't possible to merge at the moment.
