### ISSUE TITLE
"Missing required parameter weight" for LoRA merge.

### ISSUE THREAD

**Issue by bubbabug** [arcee-ai/mergekit#348]
I am attempting to use the following config file on both mergekit-gui and lazymergekit and recieving the same error on both:

```
models:
  - model: jeiku/dontusethis+ResplendentAI/Qwen_jeiku_LoRA_128
merge_method: linear
dtype: float16
```

The error:

```
[2024-06-13 03:11:25] [INFO] /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-06-13 03:11:25] [INFO] warnings.warn(
[2024-06-13 03:11:25] [INFO] Traceback (most recent call last):
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/bin/mergekit-yaml", line 8, in <module>
[2024-06-13 03:11:25] [INFO] sys.exit(main())
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
[2024-06-13 03:11:25] [INFO] return self.main(*args, **kwargs)
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/click/core.py", line 1078, in main
[2024-06-13 03:11:25] [INFO] rv = self.invoke(ctx)
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
[2024-06-13 03:11:25] [INFO] return ctx.invoke(self.callback, **ctx.params)
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/click/core.py", line 783, in invoke
[2024-06-13 03:11:25] [INFO] return __callback(*args, **kwargs)
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/options.py", line 82, in wrapper
[2024-06-13 03:11:25] [INFO] f(*args, **kwargs)
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/scripts/run_yaml.py", line 47, in main
[2024-06-13 03:11:25] [INFO] run_merge(
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/merge.py", line 78, in run_merge
[2024-06-13 03:11:25] [INFO] targets = MergePlanner(
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/plan.py", line 247, in plan_to_disk
[2024-06-13 03:11:25] [INFO] self._plan()
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/plan.py", line 285, in _plan
[2024-06-13 03:11:25] [INFO] self.plan_tensor(
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/plan.py", line 166, in plan_tensor
[2024-06-13 03:11:25] [INFO] tensor_params[model][p.name] = cfg_m.parameter(
[2024-06-13 03:11:25] [INFO] File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/mergekit/config.py", line 195, in parameter
[2024-06-13 03:11:25] [INFO] raise RuntimeError(f"Missing required parameter {name}{suffix}")
[2024-06-13 03:11:25] [INFO] RuntimeError: Missing required parameter weight for jeiku/dontusethis+ResplendentAI/Qwen_jeiku_LoRA_128.model.embed_tokens.weight
[2024-06-13 03:11:26] [ERROR] Command exited with code 1
[2024-06-13 03:11:26] [ERROR] Merge failed. Deleting repo as no model is uploaded.
```

It is the same exact error on both methods, I am assuming that at some point lora merging has been broken, as I have been usin mergekit to merge loras for many months.

**Comment by cg123** [comment]
The `linear` merge method needs weights specified for all models. You can either set it to 1, like so:

```yaml
models:
  - model: jeiku/dontusethis+ResplendentAI/Qwen_jeiku_LoRA_128
    parameters:
      weight: 1.0
merge_method: linear
dtype: float16
```

Or use the `passthrough` method, which doesn't need any parameters:
```yaml
models:
  - model: jeiku/dontusethis+ResplendentAI/Qwen_jeiku_LoRA_128
merge_method: passthrough
dtype: float16
```

**Comment by bubbabug** [comment]
Wow, I took a month off and completely forgot how to do a linear merge. Thank you Charles.
