### ISSUE TITLE
qwen2-0.5B cannot be merged into MoE

### ISSUE THREAD

**Issue by letterk** [arcee-ai/mergekit#350]
```bash
Traceback (most recent call last):
  File "/home/kissoul/miniconda3/envs/factory/bin/mergekit-moe", line 8, in <module>
    sys.exit(main())
  File "/home/kissoul/miniconda3/envs/factory/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/kissoul/miniconda3/envs/factory/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/kissoul/miniconda3/envs/factory/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kissoul/miniconda3/envs/factory/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/kissoul/WORKDIR/mergekit/mergekit/options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "/home/kissoul/WORKDIR/mergekit/mergekit/scripts/moe.py", line 211, in main
    build(
  File "/home/kissoul/WORKDIR/mergekit/mergekit/scripts/moe.py", line 82, in build
    out_arch.write_model(
  File "/home/kissoul/WORKDIR/mergekit/mergekit/moe/qwen.py", line 167, in write_model
    tensor = base_loader.get_tensor(
  File "/home/kissoul/WORKDIR/mergekit/mergekit/io/lazy_tensor_loader.py", line 127, in get_tensor
    raise KeyError(key)
KeyError: 'lm_head.weight'
```

```bash
Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm()
        (post_attention_layernorm): Qwen2RMSNorm()
      )
    )
    (norm): Qwen2RMSNorm()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)
```

**Comment by letterk** [comment]
Qwen2 0.5B and 1.5B do not have an independent lm_head layer, it is shared.

**Comment by mahiatlinux** [comment]
Getting this when trying to merge 2 Qwen2 1.5B models:

```
Fetching 8 files: 100% 8/8 [00:38<00:00,  4.79s/it]
Warm up loaders: 100% 3/3 [01:10<00:00, 23.45s/it]
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-moe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/mergekit/mergekit/options.py", line 76, in wrapper
    f(*args, **kwargs)
  File "/content/mergekit/mergekit/scripts/mixtral_moe.py", line 453, in main
    build(
  File "/content/mergekit/mergekit/scripts/mixtral_moe.py", line 326, in build
    tensor = base_loader.get_tensor(tensor_name)
  File "/content/mergekit/mergekit/io/lazy_tensor_loader.py", line 127, in get_tensor
    raise KeyError(key)
KeyError: 'lm_head.weight'

```

Not fully resolved?

**Comment by letterk** [comment]
@mahiatlinux Have you not updated mergekit?

**Comment by mahiatlinux** [comment]
> @mahiatlinux Have you not updated mergekit?

I just noticed I only get this error on the MoE branch. Sorry for the trouble.

**Comment by David-AU-github** [comment]
@mahiatlinux 

Built a Llama 3.2 - 8X3B (18.4B parameters) this way:

Found if you patched mergekit\_data\architectures\mistral.json as follows; it works:

```
 "post_weights": [
        {
            "name": "model.norm.weight",
            "input_space": "h_${num_layers}"
        },
        {
            "name": "lm_head.weight",
            "input_space": "h_${num_layers}",
            "is_embed": true,
	            "aliases": [
                "model.embed_tokens.weight"
            ]
        }
    ]
```

YOU MAY want to revert it back for "normal" use:

    "post_weights": [
        {
            "name": "model.norm.weight",
            "input_space": "h_${num_layers}"
        },
        {
            "name": "lm_head.weight",
            "input_space": "h_${num_layers}",
            "is_embed": true
        }
    ]

Important:
Note the "," after "is_embed": true,  
and
"aliases": [
                "model.embed_tokens.weight"
            ]
which is added in part 1.

I mention reverting, because there is no telling what will happen with models W lm_head.weight AND "embed_tokens..."
