### ISSUE TITLE
[request] Llama 3.1 Support

### ISSUE THREAD

**Issue by discordianbelle** [arcee-ai/mergekit#380]
Hello! Just wanted to makes sure you were aware that Llama 3.1 is currently not supported.

The rope scaling portion of config.json for L3.1 is like so:

"""
  "rope_scaling": {
    "factor": 8.0,
    "low_freq_factor": 1.0,
    "high_freq_factor": 4.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
"""

therefore mergekit throws the following error:

"""
config.json: 100%|█████████████████████████████| 913/913 [00:00<00:00, 1.58MB/s]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mergekit/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/raven/mergekit/mergekit/options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "/Users/raven/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/Users/raven/mergekit/mergekit/merge.py", line 50, in run_merge
    model_arch_info = [
  File "/Users/raven/mergekit/mergekit/merge.py", line 51, in <listcomp>
    get_architecture_info(m.config(trust_remote_code=options.trust_remote_code))
  File "/Users/raven/mergekit/mergekit/common.py", line 125, in config
    res = AutoConfig.from_pretrained(
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 952, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/transformers/configuration_utils.py", line 761, in from_dict
    config = cls(**config_dict)
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "/opt/miniconda3/envs/mergekit/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 181, in _rope_scaling_validation
    raise ValueError(
**ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}**
"""

**Comment by discordianbelle** [comment]
Just needed to update transformers, PIBCAK

**Comment by discordianbelle** [comment]
Problem was me, I didn't update transformers
