### ISSUE TITLE
解决运行错误

### ISSUE THREAD

**Issue by yhyub** [arcee-ai/mergekit#402]
怎么解决mergekit-yaml qwen_sail.yaml ./fddfgh/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python\Scripts\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "D:\Python\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\PycharmProjects\pythonProject1\venv\datasets\New Folder Content\Code\New Folder\Project\mergekit-main\mergekit\options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject1\venv\datasets\New Folder Content\Code\New Folder\Project\mergekit-main\mergekit\scripts\run_yaml.py", line 44, in main
    merge_config: MergeConfiguration = MergeConfiguration.model_validate(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\pydantic\main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for MergeConfiguration
parameters.dtype.ConditionalParameter
  Input should be a valid dictionary or instance of ConditionalParameter [type=model_type, input_value='bfloat16', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
parameters.dtype.list[ConditionalParameter]
  Input should be a valid list [type=list_type, input_value='bfloat16', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/list_type
parameters.dtype.float
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='bfloat16', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/float_parsing
parameters.dtype.list[float]
  Input should be a valid list [type=list_type, input_value='bfloat16', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/list_type

**Comment by lizhipengpeng** [comment]
same error
