### ISSUE TITLE
KeyError model[0] did not exist in tensor?

### ISSUE THREAD

**Issue by FrozzDay** [arcee-ai/mergekit#446]
I am performing a Mega Merge using LLaMA 3.2 3B, both the base model and fine-tuning/instruction tuning, with the DARE linear method. Following the successful completion of the initial merge, I encountered an error when attempting to merge the second one. The error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-mega", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mergekit/options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mergekit/scripts/megamerge.py", line 187, in main
    merge(m, merge_options, force, out_path)
  File "/usr/local/lib/python3.10/site-packages/mergekit/scripts/megamerge.py", line 81, in merge
    run_merge(
  File "/usr/local/lib/python3.10/site-packages/mergekit/merge.py", line 96, in run_merge
    for _task, value in exec.run(quiet=options.quiet):
  File "/usr/local/lib/python3.10/site-packages/mergekit/graph.py", line 197, in run
    res = task.execute(**arguments)
  File "/usr/local/lib/python3.10/site-packages/mergekit/tokenizer/embed.py", line 54, in execute
    embed_size = tensors[models[0]].shape[1]
  File "/usr/local/lib/python3.10/site-packages/mergekit/tokenizer/embed.py", line 54, in execute
    embed_size = tensors[models[0]].shape[1]
KeyError: ModelReference(model=ModelPath(path='unsloth/Llama-3.2-3B', revision=None), lora=None, override_architecture=None)
```
The config is something like this
```
models:
  - model: unsloth/Llama-3.2-3B
  - model: model-1
    parameters:
      weight: 1
  - model: model-2
    parameters:
      weight: 1
merge_method: dare_linear
base_model: unsloth/Llama-3.2-3B
tokenizer_source: model-1
parameters:
dtype: float32
```

**Comment by David-AU-github** [comment]
Confirming exact same error ; mergekit can not find the "base_model"  ; including if the path is local (absolute) on windows.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\mergekit3\mergekit\mergekit\options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "F:\mergekit3\mergekit\mergekit\scripts\run_yaml.py", line 47, in main
    run_merge(
  File "F:\mergekit3\mergekit\mergekit\merge.py", line 96, in run_merge
    for _task, value in exec.run(quiet=options.quiet):
  File "F:\mergekit3\mergekit\mergekit\graph.py", line 197, in run
    res = task.execute(**arguments)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\mergekit3\mergekit\mergekit\merge_methods\generalized_task_arithmetic.py", line 126, in execute
    tvs, base = get_task_vectors(
                ^^^^^^^^^^^^^^^^^
  File "F:\mergekit3\mergekit\mergekit\merge_methods\generalized_task_arithmetic.py", line 201, in get_task_vectors
    base = tensors[base_model]
           ~~~~~~~^^^^^^^^^^^^
KeyError: ModelReference(model=ModelPath(path='G:/9B/gemma2-gutenberg-9B', revision=None), lora=None, override_architecture=None)

**Comment by David-AU-github** [comment]
@cg123 Thank you so much.;
