### ISSUE TITLE
[Bug] "Mega merging" seems to no longer be supported.

### ISSUE THREAD

**Issue by T145** [arcee-ai/mergekit#477]
This example: https://github.com/arcee-ai/mergekit/blob/main/examples/mega.yml

Fails with this error:
```
~> mergekit-yaml .\qwen-test.yml .\output\test\   
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "{env}\Scripts\mergekit-yaml.exe\__main__.py", line 8, in <module>
  File "{env}\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\mergekit\options.py", line 82, in wrapper
    f(*args, **kwargs)
  File "{env}\Lib\site-packages\mergekit\scripts\run_yaml.py", line 45, in main
    yaml.safe_load(config_source)
  File "{env}\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "{env}\Lib\site-packages\yaml\composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    slices:
    ^
but found another document
  in "<unicode string>", line 18, column 1:
    ---
    ^
```

Using `mergekit` version `0.0.5.1`.

**Comment by cg123** [comment]
Mega merges use a different entry point - use  `mergekit-mega ./examples/mega.yaml` and it should work.
